- datadog_callback.py
Use a more conservative approach as to the existence of the `changed`
key.
This could be extended to all the keys that are used on dicts passed
to the callback (as afaik Ansible doesn't provide any guarantee of their
existence), but for now a case-by-case approach may be enough.
> Fix KeyError on `res` argument passed to `runner_on_ok`

- datadog_callback.py
Task example for no_log: True. Leads to missing invocation key as well.
```
- name: create new secret
shell: openssl rand -base64 32
register: my_secret
no_log: true
```
Value of result:
```
{'censored': 'results hidden due to no_log parameter', 'changed': True, 'rc': 0}
```
Cheers :beers: 
Daniel
> Handle no_log: True and missing invocation key gracefully

- datadog_callback.py
> Avoid failing when res['invocation'] has no `module_name` key

- CHANGELOG.md
- datadog_callback.py
Check for datadog and yaml libraries before starting.
> Check for datadog and yaml libraries

- CHANGELOG.md
- datadog_callback.py
Hi, I use ansible datadog_callback.yml plugin.
Usually plugin output datadog-agent's info level to ansible.log.
Like this.
```
2017-06-12 16:16:54,344 requests.packages.urllib3.connectionpool https://app.datadoghq.com:443 "POST /api/v1/events?api_key=key HTTP/1.1" 202 336
2017-06-12 16:16:54,344 datadog.api 202 POST https://app.datadoghq.com/api/v1/events (673.3ms)
```
I fixed output only warning level.
Thanks,
> Set log level for datadog agent

- CHANGELOG.md
- README.md
- datadog_callback.py
Enables setting the datadog API key using file at custom location or environment variable
> Added two environment variables for configuring datadog api key

- datadog_callback.py
When `ignore_errors` is `True`, user don't expect to see an error event coming up.
> Don't post if ignore_errors is True

- README.md
Found a small typo in the README file. Fixed it.
> Fixing a typo in README.md file

- README.md
Documents OpenSSL requirement for Mac OS X users running OS-installed versions of python (e.g. python 2.7.10). Raised in support case where user's Ansible events were not getting sent to Datadog. 
Reference: https://github.com/kennethreitz/requests/issues/3883#issuecomment-281182498
> adds openssl requirement note for macosx users

- datadog_callback.py
I was seeing this in my Ansible plays:
`YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.`
Per https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation I added the Loader argument.
> Added loader argument for yaml.load

- README.md
- datadog_callback.py
There have been some changes with ansible 2.8 that aren't compatible with 2.7. I've added a check to handle those differences.
> add hook to handle incompatibilities between ansible 2.7 and ansible 2.8

- datadog_callback.py
When using a vaulted variable the API key is returned with the type: ansible.parsing.yaml.objects.AnsibleVaultEncryptedUnicode ([ref](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/yaml/objects.py#L86)), where as datadogpy expects the type: String ([ref](https://github.com/DataDog/datadogpy/blob/058114cc3d65483466684c96a5c23e36c3aa052e/datadog/__init__.py#L51-L52)). The result is that the API fails to parse the Ansible type and the following (403) error is returned by API:
```
{
"status": "error",
"code": 403,
"errors": [
"Forbidden"
],
"statuspage": "http://status.datadoghq.com",
"twitter": "http://twitter.com/datadogops",
"email": "support@datadoghq.com"
}
```
While the `AnsibleVaultEncryptedUnicode` can not be a considered a String most common python string actions …
> cast api_key as str in datadog.initialize

- README.md
- datadog_callback.py
The `README.md` change describes the changes in this PR.
> Explain Ansible/Datadog hostname mismatch, allow overriding hostname

- datadog_callback.py
`error_hosts` already contains converted hostnames, so don't call `get_dd_hostname` on it again.
> Remove extraneous call of hostname conversion

- README.md
- requirements.txt
This PR improves user experience by providing a `requirements.txt` file that users may utilize to install dependencies and it also specifies minimum required version of `pyyaml` (with any older version, the callback fails).
> Add requirements.txt file, require pyyaml >= 5.1

- datadog_callback.py
- requirements.txt
Per an offline user request, this implements pyyaml < 5.1 support.
> Support pyyaml < 5.1

- .github/workflows/codeql-analysis.yml
Static code analysis on ansible-datadog-callback using Github's Code Scanning.
This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to master branch. As of now only default security based CodeQL queries are configured. We can gradually add queries for Code Quality later. It is a part of Datadog compliance requirements to regularly perform code-scanning on all the customer installed code. As the repository is small, no security alerts were found during the scan.
> Setting up codescanning for ansible-datadog-callback

- datadog_callback.py
When using Ansible to create Datadog monitors, the events we create here
could contain @mentions meant to appear in the monitor message. When
an event contains an @mention, Datadog notifies the team @mentioned.
This could cause teams to be notified or paged when the monitor is created.
This replaces @mentions with (@)mentions, preventing the notification.
> Replace @ in events to avoid notifying @mentions

- datadog_callback.py
Fix `cannot import name 'cli' from '__main__'` error
* Closes #69
> Fix `cannot import name 'cli' from '__main__'` error

- .github/CODEOWNERS
This PR updates the codeowners to the updated team name Agent Delivery
> chore(codeowners): update barx to agent-delivery

- requirements.txt
It is good practice to keep entries in requirements.txt sorted.
No functional change.
> requirements.txt: sort entries
